spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=8081

# Database
spring.datasource.url=jdbc:mariadb://database-1.czsam4aacdw5.ap-northeast-2.rds.amazonaws.com:3306/db_codingrecipe?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=admin
spring.datasource.password=12340000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# Thymeleaf
spring.thymeleaf.cache=false

# Spring Data JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework=DEBUG
logging.level.com.codingrecipe=DEBUG

# Spring Security
spring.security.debug=true


